main: at.srsyntax.farmingworld.FarmingWorldPlugin
name: FarmingWorld
version: ${version}
api-version: 1.18

author: SrSyntaxAT
website: https://srsyntax.at/

commands:
  farming:
    aliases:
      - farm
      - farmworld
      - farmingworld
      - farmwelt
    description: Teleport you to a farming world.
  farmingworldinfo:
    aliases:
      - fwi
    description: Show current information of the FarmingWorld.
  farmingworldreset:
    aliases:
      - fwr
    description: Reset a Farming World.