main: at.srsyntax.farmingworld.FarmingWorldPlugin
name: FarmingWorld
version: ${version}
api-version: 1.19

softdepend:
  - Vault

author: SrSyntaxAT
website: https://srsyntax.at/

commands:
  farming:
    description: Teleport yourself or another player to a farm world
  fwa:
    description: A command to manage the farm worlds